### ISSUE TITLE
contextily fails to import

### ISSUE THREAD

**Issue by NYSAG-GS** [NYAG/dockers#84] opened 2020-05-13 04:14 UTC
`import contextily` fails in a new dumpling container. Importing works after switching to python 3.8.1 `pyenv global 3.8.1` and installing `pip install contextily`

**Comment by NYSAG-GS** [comment] 2020-05-13 04:15
error is
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/contextily/__init__.py", line 5, in <module>
    from . import tile_providers as sources
  File "/usr/local/lib/python3.5/dist-packages/contextily/tile_providers.py", line 37
    return globals()[f'_{name}']
                              ^
SyntaxError: invalid syntax
```

**Comment by joe-graham-oag** [comment] 2020-05-13 14:46
It looks like contextily only supports Python 3.6+, through its use of f-strings. But it looks like contextily's setup.py states they should support Python 3.5. I'll move this package to our 3.8 install in the near term and look into opening an issue with contextily.

**Comment by joe-graham-oag** [comment] 2020-05-13 16:52
Contextily confirmed they only support 3.6 as well, requested they add that to their setup.py but closing this with next commit, contextily will be provided by 3.8.

**Closed** 2020-05-13 16:53 UTC
Labels: bug
